### PR TITLE
Development

### PR DESCRIPTION
**Pull request by shubham14p3**
Basic Minimal Commits made for Microverse Review
- HTML Updated
- CSS Updated
- W3 Validation Check
- Forms , Toggle, other tags Checked

### CODE REVIEW

**Review by nikasulo — CHANGES_REQUESTED** [review]
# Under Review By Tolulope Olusakin(TSE)
Please check on this in a few minutes for some feedback! :+1:

**Review by nikasulo — CHANGES_REQUESTED** [review]
# Great work @shubham14p3 :clap: 
Your work looks really great, however, there is a mini-challenge with the alignment of the form taking into account the logos just above it. Please ensure that both the logos and the form sit in the middle of the page and request another review! I wish you the best and see you at the top :rocket: 
screenshot

##### Think I missed something? Need some help with this or any of your projects? Please feel free to reach out to me on [Twitter](https://twitter.com/oluwadamilareo_) or [Instagram](https://instagram.com/oluwadamilare_olusakin), even if you just want to chat and I will respond to you as soon as I can.

**Comment by addod19** [comment]
## Pull Request under review by Daniel Larbi Addo (TSE)

**Review by addod19 — CHANGES_REQUESTED** [review]
## Status: Require changes 🔴

Hi @shubham14p3, great job in implementing the comments pointed out by the previous reviewer 👍 
However, we have one important fix I need to point out to be fixed before we can approve your project.
Find comment below:
- Kindly enable a stickler for the repo on this [link](https://stickler-ci.com/). Log in with your Github account and enable a stickler for the repo in use. Make sure to pass all the stickler checks and submit another code review. 😄 

Good luck with your next submission ✋ 
_Happy coding_ 👨‍💻 
Find me on @slack => **Daniel Larbi Addo**

**Review by addod19 — APPROVED** [review]
## Status: Approved 🏆 🎈 

Hi @shubham14p3,  😄 **congratulations** on a great job fixing all the requested changes pointed out by the previous reviewers 👐 

Go ahead and merge to master and submit the project completion form 👍 
_Happy coding_ 👨‍💻 
[Daniel Larbi Addo](https://www.linkedin.com/in/daniel-larbi-addo-9738b0128/)

**Pull request merged**
